default: &default
  type: sqlite
  synchronize: false
  entities:
    - src/cats/entities/cat.entity.ts
    - src/users/entities/user.entity.ts
  migrations:
    - src/migrations/*.ts
  cli:
    migrationsDir: src/migrations

development:
  <<: *default
  synchronize: true
  database: db/development.sqlite3

test:
  <<: *default
  synchronize: true
  database: db/test.sqlite3
