default: &default
  type: sqlite
  synchronize: false
  cli:
    migrationsDir: src/migrations

development:
  <<: *default
  database: db/development.sqlite3
  entities:
    - dist/**/*.entity.js
  migrations:
  - dist/src/migrations/*.js

test:
  <<: *default
  database: db/test.sqlite3
  entities:
    - src/**/cat.entity{.js,.ts}
    - src/**/user.entity{.js,.ts}
  migrations:
    - src/migrations/*.ts
