name: CI

on:
  push:
    branches: ['*']

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - name: Run core tests
        run: npm run test
      - name: Run end-to-end tests
        run: npm run test:e2e